name: Arcana
description: Arcana template for Jekyll
paginate: 10
baseurl: '/school-website'
collections:
  staff:
    permalink: /staff/:path/
    output: true
defaults:
  -
    scope:
      path: ""
      type: staff
    values:
      name: "Unnamed"
      role: "None"
      image_path: '/school-website/assets/images/profile.png'
      description: ""
      layout: staff
